format = '$all$character$line_break'
# Don't print a new line at the start of the prompt
add_newline = false
scan_timeout = 2
# A continuation prompt that displays two filled-in arrows
continuation_prompt = '▶▶ '

[line_break]
disabled = false

[character]      # The name of the module we are configuring is "character"
success_symbol = "[➜](bold yellow)"
error_symbol   = "[➜](bold red)"
vicmd_symbol   = "[](bold blue)"

[docker_context]
#disabled = false

[kubernetes]
disabled = true

[directory]
fish_style_pwd_dir_length = 1
style = 'cyan'

[time]
disabled = false
format = ' [ $time ]($style) '
time_format = '%T'
