# Don't print a new line at the start of the prompt
add_newline = false
scan_timeout = 2

[character]      # The name of the module we are configuring is "character"
success_symbol = "[➜](bold yellow)"
error_symbol   = "[➜](bold red)"
vicmd_symbol   = "[](bold blue)"

[docker_context]
#disabled = false

[kubernetes]
disabled = true

[directory]
fish_style_pwd_dir_length = 1
style = 'cyan'
