#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "molokai"
    colorscheme_bg = "dark"
#background = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_display_mode = false
    bootstrap_before = "myspacevim#before"
    enable_tabline_filetype_icon = true
#
#
# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'ctrlp'

[[layers]]
name = 'lang#javascript'
auto_fix= true
enable_flow_syntax = true

[[layers]]
name = "lang#typescript"

[[layers]]
name = "lang#csharp"

[[layers]]
name = "lang#fsharp"

[[layers]]
name = 'lang#go'
go_highlight_build_constraints = 1
go_highlight_extra_types = 1
go_highlight_fields = 1
go_highlight_functions = 1
go_highlight_methods = 1
go_highlight_operators = 1
go_highlight_structs = 1
go_highlight_types = 1

[[custom_plugins]]
name = 'w0rp/ale'
merged = 0

[[layers]]
name = 'lang#graphql'

[[custom_plugins]]
name = 'yuttie/comfortable-motion.vim'
merged = 0


[[custom_plugins]]
name = 'chriskempson/base16-vim'
merged = 0

[[layers]]
name = "colorscheme"
merged = 0

[[custom_plugins]]
name = "chrisbra/Colorizer"

[[custom_plugins]]
name = "peitalin/vim-jsx-typescript"
[[custom_plugins]]
name = "maxmellon/vim-jsx-pretty"
