[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"
http_timeout = 300
max_concurrency = 20

[imgdiff]
source = "github"
github = "n7olkachev/imgdiff"
use_max_tag = true

[owncast]
source = "github"
github = "owncast/owncast"
use_max_tag = true

[pbgopy]
source = "github"
github = "nakabonne/pbgopy"
use_max_tag = true

[whatscli]
source = "github"
github = "normen/whatscli"
use_max_tag = true

[whatscli-git]
source = "github"
github = "normen/whatscli"

[bella-git]
source = "github"
github = "tv42/bella"

[xrandr-notify]
source = "github"
github = "pjvds/randr-notify"
use_max_tag = true

[slock-git]
source = "cmd"
cmd = "$DOTFILES/nvchecker/slock-version.sh"

[naivecalendar-git]
source = "gitlab"
gitlab = "Daguhh/naivecalendar"
host = "framagit.org"
