on: 
  push:
    branches:
      - 'master'
    paths:
      - 'qmk/**'
      - '.github/workflows/qmk.yml'
  workflow_dispatch:

name: Build QMK firmware

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build crkdb born2code firmware
        run: |
          docker run \
            -v ${PWD}/qmk/build/:/qmk_firmware/.build/ \
            -v ${PWD}/qmk/crkdb/born2code:/qmk_firmware/keyboards/crkbd/keymaps/born2code \
            jonz94/qmk_firmware:0.26.7 qmk compile -kb crkbd -km born2code
      - name: Build crkdb r2g born2code firmware
        run: |
          docker run \
            -v ${PWD}/qmk/build/:/qmk_firmware/.build/ \
            -v ${PWD}/qmk/crkdb/born2code:/qmk_firmware/keyboards/crkbd/keymaps/born2code \
            jonz94/qmk_firmware:0.26.7 qmk compile -kb crkbd/r2g -km born2code
      - name: Build crkdb r2g default firmware
        run: |
          docker run \
            -v ${PWD}/qmk/build/:/qmk_firmware/.build/ \
            jonz94/qmk_firmware:0.26.7 qmk compile -kb crkbd/r2g -km default
      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: qmk/build/*.hex
