on: 
  push:
    branches:
      - 'master'
    paths:
      - 'qmk/**'
      - '.github/qmk.yml'
  workflow_dispatch:

name: Build QMK firmware

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: qmk
    container:
      image: zmkfirmware/zmk-build-arm:2.5
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build firmware
        run: |
          mkdir build; \
          docker run \
            -v build:/qmk_firmware/.build \
            -v crkdb/born2code:/qmk_firmware/keyboards/crkbd/keymaps/born2code \
            jonz94/qmk_firmware qmk compile -kb crkbd -km born2code

      - name: Archive firmware
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: build/*.hex
